import java.util.Scanner; 

//1.2.27 Gaussian random numbers.
/*
Write a program RandomGaussian
that prints a random number r drawn from the Gaussian distribution. One way to 
do so is to use the Box–Muller formula
r = sin(2 pi v) (-2 ln u)1/2
where u and v are real numbers between 0 and 1 generated by the Math.random()
method.
*/
 public class HSO5 {
 public static void main(String[] args) {
	 double u = Math.random();
	 double v = Math.random();
	 double bir =2*Math.PI*v;
	 double iki=(-2*Math.log(u));
	 double sinBir = Math.sin(bir);
	 double sqrtIki=Math.sqrt(iki);
	 double r=sinBir*sqrtIki;
	 System.out.println("u değeri :  "+u);
	 System.out.println("v değeri :  "+v);
	 System.out.println("r değeri :  "+r);
	 }
	} 